### ISSUE TITLE
Excellon cant be panelized

### ISSUE THREAD

**Issue by MiracelVip** [vika-sonne/FlatCAM#1]
Unfornuatly same bug like in the original version. If you try to panalize the excellon you get this error mesage:

`New object with name: Gerber_BottomLayer.GBL_panelized. 0.177734 seconds executing initialize(). [SUCCESS] Panel created successfully. [SUCCESS] Done. Generating panel ...  Generating panel... Spawning copies: 8 Generating panel ... Adding the source code. [ERROR] An internal error has occurred. See shell. **Object (excellon) failed because: 'App' object has no attribute 'export'**   Traceback (most recent call last):   File "C:\Users\Werkstatt\Downloads\FlatCAM_2024_4_windows_portable\FlatCAM_2024_4.zip\FlatCAM\appObjects\AppObject.py", line 160, in new_object     return_value = initialize(obj, self.app)   File "C:\Users\Werkstatt\Downloads\FlatCAM_2024_4_windows_portable\FlatCAM_2024_4.zip\FlatCAM\appTools\ToolPanelize.py", line 362, in job_init_excellon     obj_fin.source_file = self.app.export.export_excellon(obj_name=self.outname, filename=None, AttributeError: 'App' object has no attribute 'export'  [SUCCESS] Panel created successfully.`
![image](https://github.com/vika-sonne/FlatCAM/assets/28352461/0e607dbd-645d-4ac5-a75d-138b6f0e78a2)

**Comment by vika-sonne** [comment]
I figure out the problem. But i don't have valid Excellon PCB file for debugging.
@MiracelVip Could you, please,  attach simple example Excellon PCB file.

**Comment by MiracelVip** [comment]
[Gerber_soil-moisture_PCB_soil-moisture_2024-06-06.zip](https://github.com/user-attachments/files/15612588/Gerber_soil-moisture_PCB_soil-moisture_2024-06-06.zip)

Inside this zip you can find a Dill_PTH_Through.DRL generated by easyEDA

Thank you for fixing it

**Comment by vika-sonne** [comment]
Please, replace `FlatCAM_2024_4.zip` file with new attached file. Run and check new version: 2024.4a
[FlatCAM_2024_4.zip](https://github.com/user-attachments/files/15892206/FlatCAM_2024_4.zip)

I checked Penalize tool with Gerber and Drill layers of above project:
![flatcam-2024 4a-1](https://github.com/vika-sonne/FlatCAM/assets/37477430/7be00846-f63d-458b-893d-8a43b6925316)
![flatcam-2024 4a-2](https://github.com/vika-sonne/FlatCAM/assets/37477430/6c6931d9-845e-4e53-a6f4-29f4689f8330)
![flatcam-2024 4a-3](https://github.com/vika-sonne/FlatCAM/assets/37477430/bcf0cad5-39d2-4092-9419-eac09e2f0b9b)

Please, check new FlatCAM version `2024.4a` and add comment to this issue.

**Comment by MiracelVip** [comment]
I have checked it and it's working! Thank you very much for fixing it. Better than original version

**Comment by Thorgrlm** [comment]
**I solved the problem this way:**



Technical Repair & Rebuild SOP: FlatCAM 2024Target OS: Ubuntu 24.04 (Linux x86_64)

**Phase 1: Environment Setup & Extraction**
To modify the binary, we first had to deconstruct the original AppImage into a writable file system.

```
# Enter the working directory
cd /home/nest/Programas/Flatcam/

# Extract the AppImage content
./FlatCAM_beta_8.995_x86_64.AppImage --appimage-extract

# Move into the source code directory
cd squashfs-root/usr/src/FlatCAM/
```


**Phase 2: Source Code Corrections1.** 

Fixing the Panelizer Tool
We bypassed the internal error where the App object could not find the export_excellon attribute.

File: `appTools/ToolPanelize.py`
Change: Commented line 362 and added pass.
 
2. Bypassing Google OR-Tools (Protobuf Conflict)
We disabled the "Traveling Salesman" optimization to avoid the DESCRIPTOR error in Ubuntu 24.04.

File: camlib.py
Action:
Python
```
# Around line 2970, inside optimized_ortools_basic:def optimized_ortools_basic(self, locations):
   return locations  # Forced bypass
```

3. Fixing Coordinate Indexing
Since optimization was disabled, we updated the G-Code generator to read raw coordinates instead of list indices.
File: `camlib.py`
Action:
Python
```
# Around line 3340, inside excellon_tool_gcode_gen:
for point in optimized_path:
# Changed from locations[point][0] to:
    locx = point[0]
    locy = point[1]
```
**Phase 3: Metadata Cleanup**
Before repacking, we had to fix the Desktop Entry file which contained duplicate keys.
Bash
```
# Edit the desktop file
gedit /home/nest/Programas/Flatcam/squashfs-root/org.flatcam.FlatCAM.desktop
# CLEANUP TASKS:
# 1. Remove duplicate X-AppImage-Arch, X-AppImage-Version, X-AppImage-Name.
# 2. Simplify Categories to: Categories=Development;Electronics;
```

Phase 4: Repackaging the AppImage
We used the appimagetool to create a new, portable, and fixed executable.
Bash
```
# Return to the main folder
cd /home/nest/Programas/Flatcam/
# Download the packaging tool
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage
# Set architecture and build
export ARCH=x86_64
./appimagetool-x86_64.AppImage --appimage-extract-and-run squashfs-root FlatCAM-Fixed.AppImage
```

<img width="1227" height="795" alt="Image" src="https://github.com/user-attachments/assets/be0af91e-2163-4a50-818a-cb92164c583f" />

<img width="1227" height="795" alt="Image" src="https://github.com/user-attachments/assets/49ae02da-010d-4390-8f96-f01a421f4fda" />

**The repaired software: I've uploaded it to my Dropbox account. I'm not sure if this is correct or not. If it isn't, I'll delete it, or have an administrator delete it.**

https://www.dropbox.com/scl/fi/20p97rmj3u7buogkmf9se/FlatCAM-Fixed.AppImage?rlkey=40akt0iewdfrd0mmly8lzqm44&st=6rnjkaqe&dl=0
